version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - pocketbase
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
    volumes:
      - ./frontend:/app/frontend

  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - pocketbase_data:/pb_data

volumes:
  pocketbase_data:
    driver: local
